version: '3.8'

# Definition of services
services:
  lamp-like:
    build:
      context: .
      dockerfile: Dockerfile_Lamp_Like
    container_name: Lamp-Like
    restart: always
    # Definition of ports
    ports:
      - "80:80"
      - "443:443"
    # Definition of volumes
    volumes:
      - /opt/www:/app
